//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdFinal1Entities : DbContext
    {
        public bdFinal1Entities()
            : base("name=bdFinal1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Cliente> T_Cliente { get; set; }
        public virtual DbSet<T_Reservacion> T_Reservacion { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
