//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Reservacion
    {
        public int ReservaId { get; set; }
        public System.DateTime FechaReserva { get; set; }
        public int ClienteId { get; set; }
    
        public virtual T_Cliente Cliente { get; set; }
    }
}
